# Kit configuration file.
# Please modify this before running for the first time.

#--------------------------------#
#       SERVER INFORMATION       #
#--------------------------------#
NetworkID: ''
ServerID: ''
ServerContactEmail: 'support@mcuni.org'
ServerContactName: 'MCUni Support'

#--------------------------------#
#     WHITELIST INFORMATION      #
#--------------------------------#
# The whitelist will allow anyone with a role greater than or equal to the one provided to connect
# You can add multiple roles in CSV format (e.g. '5,6,7,9')
# Whitelist roles:
# 1 - Non-ranked users
# 2 - Members
# 5 - Society Members
# 6 - Society Team
# 7 - Server Team
# 9 - MCUni Admins

WhitelistOn: false
WhitelistRoles: '5'

#--------------------------------#
#         API CONNECTION         #
#--------------------------------#
APIKey: ''

#--------------------------------#
#        CONSOLE MESSAGES        #
#--------------------------------#
LogWhitelistInfo: true
LogBroadcastInfo: true
LogDebugInfo: false
LogAPICalls: false