name: MCUni-Kit
version: '${project.version}'
main: org.mcuni.kit.Kit
api-version: 1.19
authors: [ LewisMilburn, MCUniDev ]
description: Kit is MCUni's unified plugin.
website: https://mcuni.org
commands:
  kit:
    description: Main command
    usage: /<command>