name: MCUni-Kit
version: 1.2
main: org.mcuni.kit.Kit
api-version: 1.19
authors: [ LewisMilburn, MCUniDev ]
description: Kit is MCUni's unified plugin.
website: https://mcuni.org
commands:
  kit:
    description: Main command
    usage: /<command>
  event:
    description: Events command
    usage: /<command>
permissions:
  kit.admin:
    description: Gives access to all Kit commands.
    children:
      kit.events: true
  kit.events:
    description: Gives access to events commands.
    default: op